In [11]:
import numpy as np
import statistics
import scipy.stats as st

In [6]:
l = [1, 2, 3, 4, 4]

In [7]:
statistics.mean(l)

2.8

In [8]:
np.mean(l)

2.8

In [9]:
np.median(l)

3.0

In [10]:
np.var(l)

1.3599999999999999

In [12]:
st.mode(l)

ModeResult(mode=array([4]), count=array([2]))

In [14]:
one_d = np.random.randint(0, 20, 20)
one_d

array([15,  1,  1,  7,  5,  0,  5, 15,  2, 10,  7, 11,  9, 16, 10, 19,  7,
        3, 13,  0])

In [16]:
one_d.shape

(20,)

In [30]:
two_d = one_d.reshape(4, 5)
two_d

array([[15,  1,  1,  7,  5],
       [ 0,  5, 15,  2, 10],
       [ 7, 11,  9, 16, 10],
       [19,  7,  3, 13,  0]])

In [31]:
np.mean(two_d)

7.8

In [32]:
np.mean(two_d, axis=0) # across the rows - i.e. for each column

array([10.25,  6.  ,  7.  ,  9.5 ,  6.25])

In [1]:
np.mean(two_d, axis=1) # across the cols - i.e. for each row

NameError: name 'np' is not defined