# Numpy Basics

## Basics

In [2]:
import numpy as np

In [3]:
a = [1, 2, 3]

In [4]:
type(a)

list

In [5]:
b = np.array(a)
type(b)

numpy.ndarray

In [6]:
np.array(range(0, 10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(0, 5, 6)

array([0., 1., 2., 3., 4., 5.])

In [9]:
np.linspace(0, 3, 31)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. ])

In [10]:
c = [[1, 2, 3], [10, 11, 12]]

In [11]:
np.array(c)

array([[ 1,  2,  3],
       [10, 11, 12]])

In [12]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
first_thirty = np.linspace(0, 29, 30)
first_thirty

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29.])

In [15]:
first_thirty.reshape((3, 10))

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.]])

## Array operations

In [16]:
a = [1, 2, 3]

In [17]:
a[2]

3

In [18]:
first_ten = np.arange(0, 10)
first_ten

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
first_ten[3]

3

In [20]:
first_ten[3:5]

array([3, 4])

In [21]:
first_ten[:2]

array([0, 1])

In [22]:
first_ten[6:]

array([6, 7, 8, 9])

In [27]:
three_by_ten = first_thirty.reshape(3, 10)
three_by_ten

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.]])

In [30]:
three_by_ten[1, :]

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [31]:
three_by_ten[:, 2]

array([ 2., 12., 22.])

In [32]:
tens = np.arange(0, 101, 10)
tens

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [35]:
geq60 = tens[tens >= 60]
geq60

array([ 60,  70,  80,  90, 100])

## More Array Operations

In [36]:
first_ten = np.arange(0, 11)
first_ten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
first_ten + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [38]:
first_ten - 10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [39]:
first_ten + first_ten

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [40]:
first_ten*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [41]:
first_ten*first_ten 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [42]:
first_ten[0] = 10
first_ten

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
first_ten[:] = 10
first_ten

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [45]:
first_ten = np.arange(0, 10)

In [46]:
first_five = first_ten[:5]
first_five

array([0, 1, 2, 3, 4])

In [48]:
first_five[:] = 0
first_five

array([0, 0, 0, 0, 0])

In [49]:
first_ten

array([0, 0, 0, 0, 0, 5, 6, 7, 8, 9])