In [31]:
import math

import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [9]:
import time

a = np.random.rand(10000000)
b = np.random.rand(10000000)
tic = time.time()
c = np.dot(a, b)
toc = time.time()
print(f"c = {c}")
print(f"Vectorized version: {1000 * (toc - tic)}ms")

c = 0
tic = time.time()
for i in range(len(a)):
    c += a[i] * b[i]
toc = time.time()

print(f"c = {c}")
print(f"Loop version: {1000 * (toc - tic)}ms")
# more than 1000x performance increase!

c = 2499644.4701171992
Vectorized version: 0.0ms
c = 2499644.470116856
Loop version: 5221.790552139282ms


In [33]:
np.random.seed(42)
A = np.random.rand(1000, 1000)
v = np.random.rand(1000)

# matrix vector mult
tic = time.time()
c = np.dot(A, v)
toc = time.time()
print(f"c = {c.shape}\n{c[:5]}")
print(f"Vectorized version: {1000 * (toc - tic)}ms\n")

c = np.zeros((1000,))
tic = time.time()
for i in range(1000):
    for j in range(1000):
        c[i] += A[i][j] * v[j]
toc = time.time()
print(f"c = {c.shape}\n{c[:5]}")
print(f"Loop version: {1000 * (toc - tic)}ms\n")
# again more than 1000x performance increase

# applying functions
tic = time.time()
c = np.exp(v)
toc = time.time()
print(f"c = {c.shape}\n{c[:5]}")
print(f"Vectorized version: {1000 * (toc - tic)}ms\n")

c = np.zeros((1000,))
tic = time.time()
for i in range(1000):
    c[i] = math.exp(v[i])
toc = time.time()
print(f"c = {c.shape}\n{c[:5]}")
print(f"Loop version: {1000 * (toc - tic)}ms\n")
# here the difference is not so staggering

c = (1000,)
[245.15317529 260.52966772 254.49075119 251.33992542 254.67090091]
Vectorized version: 0.0ms

c = (1000,)
[245.15317529 260.52966772 254.49075119 251.33992542 254.67090091]
Loop version: 844.264030456543ms

c = (1000,)
[1.81331312 1.44010661 1.00539009 1.75257779 2.45118213]
Vectorized version: 0.0ms

c = (1000,)
[1.81331312 1.44010661 1.00539009 1.75257779 2.45118213]
Loop version: 0.0ms

