In [2]:
import numpy as np

A = np.array([
    [56., 0.0, 4.4, 68.0],
    [1.2, 104., 52.0, 8.0],
    [1.8, 135.0, 99.0, 0.9]
])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [5]:
cal = A.sum(axis=0)
print(cal)
print(cal.reshape(1, 4))

[ 59.  239.  155.4  76.9]
[[ 59.  239.  155.4  76.9]]


In [7]:
percentage = 100 * A / cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [8]:
v = np.array([1, 2, 3, 4])
v + 100

array([101, 102, 103, 104])

In [9]:
B = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B + np.array([100, 200, 300])

array([[101, 202, 303],
       [104, 205, 306]])

In [10]:
a = np.random.randn(5)
a

array([-0.76738367, -0.9918401 ,  1.76225283,  0.98989516,  1.10993427])

In [11]:
a.shape

(5,)

In [12]:
a.T

array([-0.76738367, -0.9918401 ,  1.76225283,  0.98989516,  1.10993427])

In [13]:
# in stead!!!
a = np.random.randn(5, 1)
a

array([[-0.44284027],
       [ 0.16485209],
       [ 1.34929878],
       [-2.11569522],
       [ 0.39750142]])

In [14]:
a.shape

(5, 1)

In [20]:
assert a.T.shape == (5, 1), "a has wrong shape"

AssertionError: a has wrong shape

In [22]:
a = np.random.rand(3, 4)
b = np.random.rand(4, 1)

a + b.T

array([[0.88993989, 0.35039824, 1.01160872, 0.68114335],
       [1.39898721, 0.19600211, 0.57008442, 1.15362402],
       [0.62526075, 0.37572002, 1.05077234, 1.25026404]])

In [27]:
c = np.zeros((3, 4))
for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]
c

array([[0.88993989, 0.35039824, 1.01160872, 0.68114335],
       [1.39898721, 0.19600211, 0.57008442, 1.15362402],
       [0.62526075, 0.37572002, 1.05077234, 1.25026404]])

In [29]:
a= np.random.randn(3,3)

b = np.random.randn(3, 1)

c = a*b
c

array([[-1.05642283, -0.28979487, -0.59008783],
       [ 0.45725841,  0.0870305 ,  0.4254234 ],
       [-1.31463796, -0.74677897, -1.32268785]])